### ISSUE TITLE
"No module named 'importlib_metadata'" on python3.8

### ISSUE THREAD

**Issue by fphammerle** [WanzenBug/pylint-import-requirements#17]
When running `pipenv lock` on python v3.6.9 my `Pipfile.lock` contains:
```
"importlib-metadata": {
    "hashes": [
        "sha256:2a688cbaa90e0cc587f1df48bdc97a6eadccdcd9c35fb3f976a09e3b5016d90f",
        "sha256:34513a8a0c4962bc66d35b359558fd8a5e10cd472d37aec5f66858addef32c1e"
    ],
    "markers": "python_version < '3.8'",
    "version": "==1.6.0"
},
```

when I re-using the same `Pipfile.lock` for python 3.8 I get:
```
 $ pipenv run pylint --persistent=n --score=n --load-plugins=pylint_import_requirements test_module
 Traceback (most recent call last):
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/bin/pylint", line 8, in <module>
     sys.exit(run_pylint())
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
     PylintRun(sys.argv[1:])
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/pylint/lint/run.py", line 250, in __init__
     linter.load_plugin_modules(self._plugins)
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 498, in load_plugin_modules
     module = modutils.load_module_from_name(modname)
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/astroid/modutils.py", line 203, in load_module_from_name
     return load_module_from_modpath(dotted_name.split("."), path, use_sys)
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/astroid/modutils.py", line 245, in load_module_from_modpath
     module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
   File "/usr/local/lib/python3.8/imp.py", line 244, in load_module
     return load_package(name, filename)
   File "/usr/local/lib/python3.8/imp.py", line 216, in load_package
     return _load(spec)
   File "<frozen importlib._bootstrap>", line 702, in _load
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/root/.local/share/virtualenvs/test_module-GHgsdefJ/lib/python3.8/site-packages/pylint_import_requirements/__init__.py", line 24, in <module>
     import importlib_metadata
 ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by fphammerle** [comment]
As `importlib-metadata` is part of `setup.py`'s `install_requires` ( https://github.com/WanzenBug/pylint-import-requirements/blob/bed1d1c9bad8998f746b1d339cd1261b242896bb/setup.py#L22 ) this is probably a pipenv bug

Keeping the issue for reference
