### ISSUE TITLE
support for import statements invoking custom loaders like PyGObject's gi.importer.DynamicImporter

### ISSUE THREAD

**Issue by fphammerle** [WanzenBug/pylint-import-requirements#18]
```python
$ pipenv run pylint --load-plugins=pylint_import_requirements systemctl_mqtt
************* Module systemctl_mqtt
[...]
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 154, in visit_import
    self.check_import(node, modname)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 215, in check_import
    self.check_namespace_module(node, spec, names)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 252, in check_namespace_module
    submodule_path = str(next(iter(spec.submodule_search_locations)))
TypeError: 'NoneType' object is not iterable
```

introduced by this comment: https://github.com/fphammerle/systemctl-mqtt/commit/dff96fc3a8636a8507464f1594afdd8f73e40dbc

```diff
diff --git a/setup.py b/setup.py
index 8c87ad4..2270c39 100644
--- a/setup.py
+++ b/setup.py
@@ -62,7 +62,7 @@ setuptools.setup(
     ],
     entry_points={"console_scripts": ["systemctl-mqtt = systemctl_mqtt:_main",]},
     # https://dbus.freedesktop.org/doc/dbus-python/news.html
-    install_requires=["dbus-python<2", "paho-mqtt<2"],
+    install_requires=["PyGObject<4", "dbus-python<2", "paho-mqtt<2"],
     setup_requires=["setuptools_scm"],
     tests_require=["pytest"],
 )
diff --git a/systemctl_mqtt/__init__.py b/systemctl_mqtt/__init__.py
index 8b00cac..956d718 100644
--- a/systemctl_mqtt/__init__.py
+++ b/systemctl_mqtt/__init__.py
@@ -24,6 +24,8 @@ import socket
 import typing
 
 import dbus
+# https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian
+import gi.repository.GLib
 
 import paho.mqtt.client
[...]
```

**Comment by WanzenBug** [comment]
Had a quick look. A few things I noticed:
* the commit failed on the "check 3.6" stage, but the test is actually running on 3.7?
* I get a different error on my local machine

```
Traceback (most recent call last):
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint_import_requirements/__init__.py", line 154, in visit_import
    self.check_import(node, modname)
  File "/home/mwanzenboeck/.local/share/virtualenvs/systemctl-mqtt-3ZjhM6zT/lib/python3.6/site-packages/pylint_import_requirements/__init__.py", line 220, in check_import
    resolved_origin = pathlib.Path(spec.origin).resolve()
  File "/usr/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Quickly adding some debug statements, it seems to be related to `import gi.repository.GLib`
This is the spec where it crashes:
```
ModuleSpec(name='gi.repository.GLib', loader=<gi.importer.DynamicImporter object at 0x7f160498a710>)
```

I guess custom importers are not supported 🤷‍♂️

**Comment by fphammerle** [comment]
Thanks a lot for your investigations, @WanzenBug !

For months I thought my github workflows tested against python3.5-3.8 :joy:
Turns out that several weren't python3.5 compatibel :/

I just rebased ( https://github.com/fphammerle/systemctl-mqtt/pull/2/commits/fb0ff7f0518938c15dc2bdcd1179d0eb5f070bd9 ) and now get:
```python
[...]
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.6/site-packages/pylint_import_requirements/__init__.py", line 154, in visit_import
    self.check_import(node, modname)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.6/site-packages/pylint_import_requirements/__init__.py", line 219, in check_import
    resolved_origin = pathlib.Path(spec.origin).resolve()
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'll try to find a workaround and post it here

Thanks!

**Comment by fphammerle** [comment]
> ```
> ModuleSpec(name='gi.repository.GLib', loader=<gi.importer.DynamicImporter object at 0x7f160498a710>)
> ```
> 
> I guess custom importers are not supported

just for reference / comparison:
```diff
--- $VIRTUAL_ENV/lib/python3.6/site-packages/pylint_import_requirements/__init__.py~	2020-06-19 06:08:51.357154095 +0200
+++ $VIRTUAL_ENV/lib/python3.6/site-packages/pylint_import_requirements/__init__.py	2020-06-19 06:14:59.136012440 +0200
@@ -14,6 +14,7 @@
 """
 import importlib.util
 import pathlib
+import pprint
 import sys
 from collections import defaultdict, namedtuple
 from distutils.core import run_setup
@@ -219,6 +220,16 @@
             return
 
         # Step 5
+        pprint.pprint(
+            {
+                "modname": modname,
+                "type(spec)": type(spec),
+                "spec.has_location": spec.has_location,
+                "spec.loader": spec.loader,
+                "spec.loader_state": spec.loader_state,
+                "spec.origin": spec.origin,
+            }
+        )
         resolved_origin = pathlib.Path(spec.origin).resolve()
         known_info = self.known_files.get(resolved_origin)
         if known_info:
```

```sh
$ pipenv run pylint --load-plugins=pylint_import_requirements systemctl_mqtt
************* Module systemctl_mqtt
systemctl_mqtt/__init__.py:145:2: W0511: TODO consider message_callback_add instead (fixme)
{'modname': 'dbus',
 'spec.has_location': True,
 'spec.loader': <_frozen_importlib_external.SourceFileLoader object at 0x7fa97576d748>,
 'spec.loader_state': None,
 'spec.origin': '$VIRTUAL_ENV/lib/python3.6/site-packages/dbus/__init__.py',
 'type(spec)': <class '_frozen_importlib.ModuleSpec'>}
{'modname': 'gi.repository.GLib',
 'spec.has_location': False,
 'spec.loader': <gi.importer.DynamicImporter object at 0x7fa974eabb70>,
 'spec.loader_state': None,
 'spec.origin': None,
 'type(spec)': <class '_frozen_importlib.ModuleSpec'>}
Traceback (most recent call last):
  File "$VIRTUAL_ENV/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
[...]
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by fphammerle** [comment]
How bad would that heuristic be?
```diff
--- $VIRTUAL_ENV/lib/python3.6/site-packages/pylint_import_requirements/__init__.py~	2020-06-19 06:08:51.357154095 +0200
+++ $VIRTUAL_ENV/lib/python3.6/site-packages/pylint_import_requirements/__init__.py	2020-06-19 07:14:10.897547203 +0200
@@ -13,6 +13,7 @@
 The plugin expects a `setup.py` file to exist in the working directory
 """
 import importlib.util
+import inspect
 import pathlib
 import sys
 from collections import defaultdict, namedtuple
@@ -219,7 +220,11 @@
             return
 
         # Step 5
-        resolved_origin = pathlib.Path(spec.origin).resolve()
+        if spec.origin:
+            resolved_origin = pathlib.Path(spec.origin).resolve()
+        else:
+            resolved_origin = pathlib.Path(inspect.getfile(type(spec.loader)))
+            print('falling back to loader:', resolved_origin)
         known_info = self.known_files.get(resolved_origin)
         if known_info:
             self.visited_distributions.add(known_info.source.metadata["Name"])
```

```sh
$ pipenv run pylint --load-plugins=pylint_import_requirements systemctl_mqtt
************* Module systemctl_mqtt
systemctl_mqtt/__init__.py:145:2: W0511: TODO consider message_callback_add instead (fixme)
falling back to loader: $VIRTUAL_ENV/lib/python3.6/site-packages/gi/importer.py

------------------------------------------------------------------
Your code has been rated at 9.89/10 (previous run: 9.89/10, +0.00)
```

I am not sure how likely it would be for a custom loader to not be part of the same distribution / package

**Comment by WanzenBug** [comment]
TBH: I would just detect non-standard loaders and skip those files entirely. There are at least some dedicated module loader packages on PYPI, so I don't think we can assume loaders always come with the distribution that uses them.

Users can already use `# pylint-import-requirements: imports=` comments to suppress the "not imported" messages generated by skipping such imports
