### ISSUE TITLE
dist.files unset for packages installed via apt-get (triggers TypeError when running outside virtual env)

### ISSUE THREAD

**Issue by fphammerle** [WanzenBug/pylint-import-requirements#24]
```
 Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.8/dist-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/run.py", line 256, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/pylinter.py", line 499, in load_plugin_modules
    module.register(self)
  File "/usr/local/lib/python3.8/dist-packages/pylint_import_requirements/__init__.py", line 357, in register
    linter.register_checker(ImportRequirementsLinter(linter))
  File "/usr/local/lib/python3.8/dist-packages/pylint_import_requirements/__init__.py", line 130, in __init__
    resolved_filepaths = {x.locate() for x in distribution_files}
TypeError: 'NoneType' object is not iterable
```

patch to debug:
```diff
--- a/pylint_import_requirements/__init__.py
+++ b/pylint_import_requirements/__init__.py
@@ -126,8 +126,16 @@ class ImportRequirementsLinter(BaseChecker):
             allowed = dist_name in self.allowed_distributions
             # Get a list of files created by the distribution
             distribution_files = dist.files
-            # Resolve the (relative) paths to absolute paths
-            resolved_filepaths = {x.locate() for x in distribution_files}
+            if not distribution_files:
+                print(
+                    "dist_name={} distrubtion_files={!r}".format(
+                        dist_name, distribution_files
+                    )
+                )
+                resolved_filepaths = set()
+            else:
+                # Resolve the (relative) paths to absolute paths
+                resolved_filepaths = {x.locate() for x in distribution_files}
 
             # in python3.4 dict.get() always returns None when passing a pathlib.Path as key
             distribution_file_info = {
```

output:
```
$ pylint --load-plugins=pylint_import_requirement mymodule
dist_name=appdirs distrubtion_files=None
dist_name=certifi distrubtion_files=None
dist_name=distlib distrubtion_files=None
dist_name=zipp distrubtion_files=None
dist_name=filelock distrubtion_files=None
dist_name=importlib-metadata distrubtion_files=None
dist_name=more-itertools distrubtion_files=None
dist_name=pip distrubtion_files=None
dist_name=setuptools distrubtion_files=None
dist_name=six distrubtion_files=None
dist_name=virtualenv distrubtion_files=None
dist_name=virtualenv-clone distrubtion_files=None
dist_name=wheel distrubtion_files=None

------------------------------------
Your code has been rated at 10.00/10
```

**Comment by fphammerle** [comment]
packages with `dist.files == None` were installed via `apt-get install python3-pip ...`

**Comment by WanzenBug** [comment]
also happens on fedora 32 with python 3.8:
```
$ python -VV
Python 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
$ pylint --load-plugins=pylint_import_requirements *.py
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    load_entry_point('pylint==2.4.4', 'console_scripts', 'pylint')()
  File "/usr/lib/python3.8/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/pylint/lint.py", line 1639, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/usr/lib/python3.8/site-packages/pylint/lint.py", line 661, in load_plugin_modules
    module.register(self)
  File "/home/mwanzenboeck/devel/priv/pylint-import-requirements/pylint_import_requirements/__init__.py", line 357, in register
    linter.register_checker(ImportRequirementsLinter(linter))
  File "/home/mwanzenboeck/devel/priv/pylint-import-requirements/pylint_import_requirements/__init__.py", line 130, in __init__
    resolved_filepaths = {x.locate() for x in distribution_files}
TypeError: 'NoneType' object is not iterable
```

**Comment by WanzenBug** [comment]
So the problem seems to be that in some cases `egg-info` is a directory, containing a file called `SOURCES.txt` and sometimes its a simple file containing metadata directly.

In case its a directory, everything is working fine and `.files` is populated with contents from `SOURCES.txt`. 

However, for some distributions, `egg-info` is a file and does not provide a `SOURCES.txt`. In this case we get the above error

**Comment by WanzenBug** [comment]
Now a workaround would be to somehow associate a distribution with a directory/file at the given location (i.e. in `site-packages`). But then you notice we are talking about python packages, and the name they provide in the metadata matches the import name only about 70% of the time...

Some examples:
```
$ ls /usr/lib/python3.8/site-packages/
...
IPython/
ipython-7.12.0-py3.8.egg-info
```
the distribution name is ipython, but the import name is `IPython`

```
...
tempita/
Tempita-0.5.1-py3.8.egg-info
...
```
opposite problem here, distribution is capitalized, import is not...

@fphammerle if you have a better solution than: skip these distributions, please enlighten me

**Comment by fphammerle** [comment]
Thanks a lot for investigating this issue!

Unfortunately, I couldn't find a platform-independent way to detect what modules are part of a dist/package either :/

I would suggest we skip those packages for now.
If anybody complains, we could consider adding platform-specific detection mechanisms
